### PR TITLE
Added Swedish locale

### PR DESCRIPTION
**Pull request by loidor**

### CODE REVIEW

**Comment by lowlevl** [comment]
Hi @loidor, thanks for your quick work.
Is everything working ? Can I merge ?

**Comment by loidor** [comment]
Everything works perfectly! :) 

I was at work so I couldn't clone and push, so that's why I used the online editor.

**Comment by lowlevl** [comment]
No problem, this will close #16 
Thanks again for your work, this will be added automatically to **Duckuino** :D

**Comment by exanor** [comment]
nice

**Pull request merged**
