### PR TITLE
All "es_ES" file bugs fixed

### PR DESCRIPTION
**Pull request by adamff-dev**
Now you can use ~, ^ and `. Read the warning comment.

### CODE REVIEW

**Comment by lowlevl** [comment]
You don't have to put the whole file .-. Wait I'll fix it !

**Comment by lowlevl** [comment]
The warning comment is useless, nobody will see it, I removed it.

**Comment by lowlevl** [comment]
Did you tested the code, all is working good ? @BlueArduino20

**Comment by adamff-dev** [comment]
Yes, I've tested it and it works correctly.

**Comment by lowlevl** [comment]
Okay, closes #19 and #26 !

**Pull request merged**
