### PR TITLE
Fix < > \ in da_DK.lang

### LINKED ISSUE #21: The characters < > \ don't work in da_DK
These characters don't work, and i don't know hot to fix it. I though that i should document it here.

### PR DESCRIPTION
**Pull request by FuzzyLitchi**
I fixed these characters. All ASCII Characters work now
This fixes #21

I used this method
`sudo cat /dev/hidraw0 > scancode`
press the disered key, press Ctrl + C to stop
`hexdump scancode`

### CODE REVIEW

**Comment by lowlevl** [comment]
Closes #22.

**Comment by lowlevl** [comment]
What is your Linux distribution ? ;D

**Comment by lowlevl** [comment]
I can't find /dev/hidraw0 on Ubuntu 16.04.1LTS...

**Comment by FuzzyLitchi** [comment]
I use Ubuntu 16.04.1 LTS aswell

**Comment by FuzzyLitchi** [comment]
try runing `dmesg | grep -i keyboard | grep hidraw`

You should have something that resembles this:

[    1.776877] hid-generic 0003:0461:0010.0001: input,hidraw0: USB HID v1.10 Keyboard [NOVATEK USB Keyboard] on usb-0000:00:14.0-9/input0
[    1.832890] hid-generic 0003:0461:0010.0002: input,hidraw1: USB HID v1.10 Device [NOVATEK USB Keyboard] on usb-0000:00:14.0-9/input1

As you can see there's an hidraw0 and hidraw1

you can do `cat /dev/hidraw0` to see the scancode that the keyboard sends, but i will try to output it as a UTF-8 character which doesn't work. so if you do `cat /dev/hidraw0 > scancode` then do `hexdump scancode`
 you dump the data into a file, then read it as hex data. And then you should find the scancode. :)

**Comment by FuzzyLitchi** [comment]
Here is what `hexdump scancode` returns for me

```
0000000 0000 0000 0000 0000 0000 0064 0000 0000
0000010 0000 0000 0000 0000 0001 0000 0000 0000
0000020 0001 0006 0000 0000                    
0000028
```
The interesting part is the 0064, which is the scancode for the key between shift and z on the danish keyboard. [Here](https://upload.wikimedia.org/wikipedia/commons/1/1f/Computer_keyboard_with_danish_layout.jpg) is a danish keyboard

all of the values from hexdump are in hex, which means 0064 is actually 0x64 in base 16 and not 64 in base10.

**Comment by lowlevl** [comment]
`dmesg | grep -i keyboard | grep hidraw` returns nothing for me x)

**Comment by FuzzyLitchi** [comment]
try `dmesg | grep -i keyboard`
or `sudo dmesg | grep -i keyboard | grep hidraw`

**Comment by lowlevl** [comment]
```shell
root:~$ dmesg | grep -i keyboard 
[    1.319258] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input3
```

**Comment by FuzzyLitchi** [comment]
hmm, maybe try `sudo cat /devices/platform/i8042/serio0/input/input3`

**Pull request merged**
