### PR TITLE
Create be_BE.lang

### PR DESCRIPTION
**Pull request by KevinDenys**
Belgian dot keyboard layout

### CODE REVIEW

**Comment by KevinDenys** [comment]
Looks like backslash wont work for some reason. its alt + 92 on belgian keyboard but it wont work

**Comment by lowlevl** [comment]
Note that 92 is the char number 92 on array, not the ascii char number.

**Comment by lowlevl** [comment]
Everything done, can i accept the pull request ? @KevinDenys

**Comment by KevinDenys** [comment]
Wait so backslash is located where < > is I have to press altgr to get the \

**Comment by lowlevl** [comment]
Done ? :D Do u find how make it work ? @KevinDenys

**Comment by Thecakeisgit** [comment]
#7

**Comment by KevinDenys** [comment]
Last update incomming. Now i under stand the altgr function haha So fixed all the altgr keys

**Comment by KevinDenys** [comment]
Now it's done :smile:

**Comment by lowlevl** [comment]
Cool, thanks for the help :D @KevinDenys

**Comment by lowlevl** [comment]
Fixes #7

**Pull request merged**
