### PR TITLE
Create tr_TR.lang

### PR DESCRIPTION
**Pull request by Include-sys**
Couldn't make it work Grave Accent(`). Gave my 8 hours maybe more. Was my first time.

Paylaşım yaparken bahsetmeyi unutmayın. ;)

### CODE REVIEW

**Comment by lowlevl** [comment]
Hi @hex4d0r, thanks for your pull request ;D But you need to add your locale in the localeList file as I said here : [Wiki - How to create a locale](https://github.com/Nurrl/LocaleKeyboard.js/wiki/How-to-create-a-locale-%3F!#step-4---time-to-contribute) 
After that, I'll merge your pull request ;D

**Comment by Include-sys** [comment]
@Nurrl , I think its okay now.

**Comment by lowlevl** [comment]
Wow that was rapid ;D
Thanks for your support @hex4d0r !

**Comment by Include-sys** [comment]
:)

**Pull request merged**
