### PR TITLE
add da_DK.lang

### PR DESCRIPTION
**Pull request by FuzzyLitchi**

### CODE REVIEW

**Comment by lowlevl** [comment]
Hi @FuzzyLitchi, thanks for your request, but as I said here, [Wiki: How to create a locale ?!](https://github.com/Thecakeisgit/LocaleKeyboard.js/wiki/How-to-create-a-locale-%3F!) : 

> Then add you file name without the .lang extension in a new line in lang/localeList file (Example : en_US).

Please do it, then I'll merge your pull request :D

**Comment by FuzzyLitchi** [comment]
oh ye

**Comment by FuzzyLitchi** [comment]
sorry i have a headache

**Comment by FuzzyLitchi** [comment]
There you go

**Comment by lowlevl** [comment]
Thanks ;D

**Pull request merged**
