### PR TITLE
Add Finnish locale

### PR DESCRIPTION
**Pull request by nicou**
All characters working except for ^ ~ `

I could not figure out how to output these characters, since they are under altgr modifier and also need to be pressed twice.

### CODE REVIEW

**Comment by lowlevl** [comment]
Hi thanks for you pull request @nicougit, with ur help, the project grows up and i'm happy :smile: 
For the chars **^**, **~** and **`**, first add them in the **_initAltGr()** function ^^ (with **_altGrMap[\<num\>] = true;** like you did for **@** or **$**)
For the double key, i don't know if it's required.. Do u think a rubber ducky is placing **^** or **half-^** ?

**Comment by nicou** [comment]
These characters are behind [dead keys](https://en.wikipedia.org/wiki/Dead_key) in the Finnish layout, is there support for those?

**Comment by lowlevl** [comment]
I got dead keys too on my Keyboard @nicougit, so leave them alone, and it
will be fine, i think the same issue is present with the "Real
USBRubberDucky" so i think there is no support to have the actual char
^, ` or ~.. Just add them to the _initAltGr() function ;D

*PS: I didn't found any payload with these keys, so for now it's not a
problem :D*

**Comment by lowlevl** [comment]
Bump ! @nicougit

**Comment by nicou** [comment]
Will do that by the end of the week, been busy with other stuff :)

**Comment by lowlevl** [comment]
Np man ;D @nicougit

**Comment by nicou** [comment]
Missing key shave been added to _altGrMap[] but as said previously they don't work. It would be interesting to dig deeper into how to make characters from dead keys work, but I don't have time for it right now. Might look into it later!

**Comment by lowlevl** [comment]
Thanks anyway @nicougit for you work, i'm merging this pull request... When you got the time, feel free to open a new issue :) !
I'll think about a solution ^^

**Pull request merged**
